### ISSUE TITLE
Double-check security of reusing the signature key multiple times in one connection

### ISSUE THREAD

**Issue by DavidSchinazi** [DavidSchinazi/draft-schinazi-httpbis-transport-auth#4]
@jhoyla and @martinthomson have pointed out that there be dragons in reusing keys. We should check to see if we need to add a signature index or some other addition to the nonce to avoid reuse.

**Comment by jhoyla** [comment]
Maybe the right approach is to add a `requestContext` field?

**Comment by DavidSchinazi** [comment]
@jhoyla can you elaborate on what the exact issue is? If the key and nonce are reused without changing anything else, what is the exact problem?

**Comment by jhoyla** [comment]
I guess the threat model has to be a Person-In-Browser attacker, because we're assuming TLS is already defeated. 
One issue would be if the key and nonce were reused with a different identity, for example if the first attempt was rejected / failed.
This can (in some contexts) be used for a key recovery attack, which would allow the attacker to possibly sign things they otherwise couldn't. 
The other issue is that the identity is not bound to a single authentication. I don't think Frames have to cause an idempotent response from the server? It could be that (correctly) authenticating twice would have some side effect. A authentication might cause the server to take some action with a side effect "send the money" style.

**Comment by DavidSchinazi** [comment]
I see. Would adding the identity to the signed data be sufficient? (I'm happy to add a request context if needed but I want to understand the details)

**Comment by jhoyla** [comment]
I don't think so, because it doesn't stop an in-browser attacker replaying the credentials to try and perform some action twice. Also in the Intermediary case, I was wondering if we could structure it such that the intermediary shares the exported key with the server, which allows the server to validate the credential. The goal would be that the server doesn't have to trust that the intermediary isn't making stuff up. I'm not sure if it's sensible or secure, because even though the shared key is independent from any of the other TLS keys shared between the client and intermediary, maybe it's possible for the intermediary to lie about the key and thus change the meaning of the message. 
(The connection here being that in the case of origin validation with an intermediary, we don't want the intermediary to be able to replay requests.) 
The more I think about the signature case the closer it seems to get to a version of EAs that allows client-initiation. I need to sit down and think a bit more about what we can learn from the security model of EAs. One question that springs to mind is "do we need a `Finished` message / MAC here?" 
If not, why do we include it in EAs? 
Sorry, I'm starting to ramble. I'll leave it there.

**Comment by m4mb01t4l14n0** [comment]
I have not looked at the code in a long time (SSL_export_keying_material). Do repeated calls to the key exporter - on the same TLS connection - generate the same value?

**Comment by jhoyla** [comment]
According to RFC 8446 it should, unless there has been a resumption or a rekeying.

**Comment by DavidSchinazi** [comment]
To clarify, in TLS 1.3 repeated calls to the key exporter with the same parameters (label, context, length) will always generate the same value. In TLS 1.2 there are dragons when it comes to resumption and rekey as Jonathan points out but we can add text explaining what not to do.

I'm not convinced that an in-browser attacker is part of the threat model here, but I'm not opposed to adding a counter to the signed data in addition to the nonce to solve that attack.

Regarding intermediaries, I like the idea of having the intermediary share the nonce with the backend. I'd be inclined to mention both options (sharing the nonce and having the intermediary check auth) in that section, but I'd rather not define how that's done until someone has a use-case for it.

From looking at TLS exported authenticators (EA) it's not clear to me what purpose the Finished message serves there.

**Comment by DavidSchinazi** [comment]
I had a quick chat with @grittygrease and @davidben about this and the conclusion was that the Finished message in EA doesn't bind any more secrets together but it allows reusing the security proofs from TLS.

**Comment by m4mb01t4l14n0** [comment]
Ha! Now realizing I said the opposite of what I meant in the earlier comment.

**Comment by DavidSchinazi** [comment]
@jhoyla and I discussed this offline today. @jhoyla had isolated two issues:
1. key reuse with AEAD -- it turns that we're only reusing keys for signatures here so there is no issue
2. compromise across requests by an in-browser attacker -- we decided that this attack wan't interesting because such an attacker could also read the private key. Worth adding to security considerations though
